In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('/content/drive/MyDrive/flashflood.csv')
df.head(4)

,Date,Village_ID,Village_Name,District,SMAP_Soil_Moisture_m3_m3,Surface_Temp_C,Latitude,Longitude,SRTM_Mean_Elevation_m,SRTM_Calculated_Slope_deg,GSI_Landslide_Susceptibility,District_Rainfall_Sep2026_mm,Historical_Flood_Record,Historically_Flooded_Area
0,2026-08-01,V001,Kedarnath,Rudraprayag,0.336,23.4,30.7346,79.0669,3583,24.5,Very High,165.8,"2013, 2021",1
1,2026-08-01,V002,Badrinath,Chamoli,0.388,13.9,30.7433,79.4938,3300,18.2,High,70.7,"2013, 2021",0
2,2026-08-01,V003,Joshimath,Chamoli,0.263,22.4,30.5506,79.5660,1890,22.1,Very High,144.2,"2013, 2021",1
3,2026-08-01,V004,Dharasu,Uttarkashi,0.413,12.2,30.6869,78.3188,1020,15.4,Moderate,205.0,2013,0

In [6]:
df["GSI_Landslide_Risk"]=df["GSI_Landslide_Susceptibility"].map({"Low":0,"Medium":1,"High":2,"Very High":3})

In [7]:
df.head(3)

,Date,Village_ID,Village_Name,District,SMAP_Soil_Moisture_m3_m3,Surface_Temp_C,Latitude,Longitude,SRTM_Mean_Elevation_m,SRTM_Calculated_Slope_deg,GSI_Landslide_Susceptibility,District_Rainfall_Sep2026_mm,Historical_Flood_Record,Historically_Flooded_Area,GSI_Landslide_Risk
0,2026-08-01,V001,Kedarnath,Rudraprayag,0.336,23.4,30.7346,79.0669,3583,24.5,Very High,165.8,"2013, 2021",1,3.0
1,2026-08-01,V002,Badrinath,Chamoli,0.388,13.9,30.7433,79.4938,3300,18.2,High,70.7,"2013, 2021",0,2.0
2,2026-08-01,V003,Joshimath,Chamoli,0.263,22.4,30.5506,79.5660,1890,22.1,Very High,144.2,"2013, 2021",1,3.0

In [8]:
df=df.fillna(df.median(numeric_only=True))
x=df[["SMAP_Soil_Moisture_m3_m3","Surface_Temp_C","Latitude","Longitude","SRTM_Mean_Elevation_m","SRTM_Calculated_Slope_deg","District_Rainfall_Sep2026_mm","GSI_Landslide_Risk"]]
y=df["Historically_Flooded_Area"]

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [12]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=200,max_depth=15,min_samples_split=4,min_samples_leaf=2,random_state=50)
model.fit(x_train,y_train)
print("Model trained succesfully")

Model trained succesfully

In [14]:
from sklearn.metrics import accuracy_score,classification_report
y_pred=model.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy:{accuracy*100:.2f}%")
print(classification_report(y_test,y_pred))

Accuracy:100.00%
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00         6

    accuracy                           1.00        14
   macro avg       1.00      1.00      1.00        14
weighted avg       1.00      1.00      1.00        14

In [15]:
from sklearn.model_selection import cross_val_score
sc=cross_val_score(model,x,y,cv=5,scoring="accuracy")
print(sc)
print(f"Accuracy:{sc.mean()*100:.2f}%")

[1.         1.         1.         1.         0.92857143]
Accuracy:98.57%

In [ ]:
df=df.fillna(df.median(numeric_only=True))
x=df[["SMAP_Soil_Moisture_m3_m3","Surface_Temp_C","Latitude","Longitude","SRTM_Mean_Elevation_m","SRTM_Calculated_Slope_deg","District_Rainfall_Sep2026_mm","GSI_Landslide_Risk"]]
y=df["Historically_Flooded_Area"]

In [17]:
test=[[0.336,23.4,30.7346,79.0669,3583,24.5,165.8,3]]
pr=model.predict(test)
pr

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([1])